# Generated by Django 6.0.6 on 2026-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('role', models.CharField(choices=[('manager', '管理者/SV'), ('creator', '作成担当'), ('checker', '確認担当')], max_length=20, verbose_name='役割')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '担当者',
                'verbose_name_plural': '担当者',
                'ordering': ['id'],
            },
        ),
    ]
