# Generated by Django 6.0.6 on 2026-06-10 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='取込ファイル名')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='全体件数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='正常件数')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='警告件数')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='エラー件数')),
                ('status', models.CharField(choices=[('processing', '処理中'), ('completed', '完了'), ('failed', '失敗')], default='processing', max_length=20, verbose_name='取込状態')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='取込日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to='payments.operator', verbose_name='取込担当者')),
            ],
            options={
                'verbose_name': '取込履歴',
                'verbose_name_plural': '取込履歴',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='取込元行番号')),
                ('issue_number', models.CharField(db_index=True, max_length=50, verbose_name='発行番号')),
                ('company_name', models.CharField(max_length=255, verbose_name='会社名')),
                ('address', models.TextField(verbose_name='住所')),
                ('registration_number', models.CharField(blank=True, max_length=14, verbose_name='事業者登録番号')),
                ('payment_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='支払金額')),
                ('payment_date', models.DateField(verbose_name='支払日')),
                ('description', models.TextField(verbose_name='内訳')),
                ('campaign_name', models.CharField(blank=True, max_length=255, verbose_name='キャンペーン名')),
                ('campaign_type', models.CharField(blank=True, max_length=100, verbose_name='キャンペーン区分')),
                ('tax_type', models.CharField(choices=[('taxable_10', '税率10％'), ('non_taxable', '税考慮なし'), ('needs_confirmation', '要確認')], max_length=30, verbose_name='税区分')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='税率')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('imported', '取込済み'), ('waiting_confirmation', '確認待ち'), ('confirmed', '確認済み'), ('correction_required', '要修正'), ('error', 'エラー'), ('completed', '完了')], db_index=True, default='imported', max_length=30, verbose_name='ステータス')),
                ('has_duplicate_warning', models.BooleanField(default=False, verbose_name='重複警告')),
                ('duplicate_check_result', models.CharField(choices=[('unchecked', '未確認'), ('not_duplicate', '重複なし'), ('duplicate', '重複確定'), ('allowed', '正当な別支払')], default='unchecked', max_length=20, verbose_name='重複確認結果')),
                ('document_created_at', models.DateTimeField(blank=True, null=True, verbose_name='通知書作成日時')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_payment_records', to='payments.operator', verbose_name='確認担当者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_records', to='payments.operator', verbose_name='作成担当者')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='payments.importbatch', verbose_name='取込履歴')),
            ],
            options={
                'verbose_name': '支払対象',
                'verbose_name_plural': '支払対象',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'source_row_number'), name='unique_source_row_per_import_batch')],
            },
        ),
    ]
