# Generated by Django 6.0.6 on 2026-06-10 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_importbatch_paymentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('required_field_missing', '必須項目不足'), ('invalid_format', 'データ形式不正'), ('duplicate_issue_number', '発行番号重複'), ('duplicate_candidate', '重複候補'), ('invalid_tax_type', '税区分不正'), ('document_generation_error', '通知書作成エラー'), ('confirmation_mismatch', '確認不一致'), ('other', 'その他')], max_length=50, verbose_name='エラー種別')),
                ('error_message', models.TextField(verbose_name='エラー内容')),
                ('target_field', models.CharField(blank=True, max_length=100, verbose_name='対象項目')),
                ('error_value', models.TextField(blank=True, verbose_name='エラー値')),
                ('resolution_status', models.CharField(choices=[('unresolved', '未対応'), ('in_progress', '対応中'), ('resolved', '解消済み')], default='unresolved', max_length=20, verbose_name='対応状況')),
                ('resolution_note', models.TextField(blank=True, verbose_name='対応内容')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='発生日時')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解消日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_errors', to='payments.paymentrecord', verbose_name='支払対象')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_processing_errors', to='payments.operator', verbose_name='対応担当者')),
            ],
            options={
                'verbose_name': '処理エラー',
                'verbose_name_plural': '処理エラー',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('import', 'データ取込'), ('update', 'データ修正'), ('generate_document', '通知書作成'), ('regenerate_document', '通知書再作成'), ('confirm', '確認結果登録'), ('change_status', 'ステータス変更'), ('register_error', 'エラー登録'), ('resolve_error', 'エラー解消'), ('check_duplicate', '重複確認')], max_length=50, verbose_name='操作種別')),
                ('action_detail', models.TextField(verbose_name='操作内容')),
                ('target_field', models.CharField(blank=True, max_length=100, verbose_name='対象項目')),
                ('old_value', models.TextField(blank=True, verbose_name='変更前の値')),
                ('new_value', models.TextField(blank=True, verbose_name='変更後の値')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='payments.importbatch', verbose_name='取込履歴')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='payments.operator', verbose_name='操作者')),
                ('payment_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='payments.paymentrecord', verbose_name='支払対象')),
            ],
            options={
                'verbose_name': '作業ログ',
                'verbose_name_plural': '作業ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.CharField(max_length=500, verbose_name='ファイル保存先')),
                ('file_type', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], default='excel', max_length=20, verbose_name='ファイル形式')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='バージョン')),
                ('is_current', models.BooleanField(default=True, verbose_name='現行版')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='payments.operator', verbose_name='作成担当者')),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='payments.paymentrecord', verbose_name='支払対象')),
            ],
            options={
                'verbose_name': '作成済み支払通知書',
                'verbose_name_plural': '作成済み支払通知書',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('payment_record', 'version'), name='unique_document_version_per_payment_record')],
            },
        ),
    ]
