# Generated by Django 6.0.6 on 2026-06-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_processingerror_worklog_generateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingerror',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_errors', to='payments.importbatch', verbose_name='取込履歴'),
        ),
        migrations.AddField(
            model_name='processingerror',
            name='source_row_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='取込元行番号'),
        ),
        migrations.AlterField(
            model_name='processingerror',
            name='payment_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_errors', to='payments.paymentrecord', verbose_name='支払対象'),
        ),
    ]
