# Generated by Django 6.0.6 on 2026-06-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_processingerror_import_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmation_comment',
            field=models.TextField(blank=True, default='', verbose_name='確認コメント'),
        ),
    ]
